coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      test:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        base: auto
        paths: "src/test/"  # only include coverage in "tests/" folder
      main:  # declare a new status context "app"
        paths: "src/main/"  # remove all files in "tests/"
        base: auto

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "master"
    - "bleeding"
