#
#     AsyncMC - A fully async, non blocking, thread safe and open source Minecraft server implementation
#     Copyright (C) 2020 joserobjr@gamemods.com.br
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      test:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        base: auto
        paths: "src/test/"  # only include coverage in "tests/" folder
      main:  # declare a new status context "app"
        paths: "src/main/"  # remove all files in "tests/"
        base: auto

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "master"
    - "bleeding"
